// Generated from supabase/migrations/20261001120000_init.sql by scripts/build-demo-seed.mjs
export const demoSeed = {
  "stalls": [
    {
      "id": "japan",
      "name": "Japan",
      "sort_order": 1,
      "year_groups": "Year 5",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "india",
      "name": "India",
      "sort_order": 2,
      "year_groups": "Year 10",
      "support_type": "both",
      "amount_per_family": "LKR 5,000",
      "how_to_pay": "Last year's details, please confirm. WhatsApp the receipt to Chandi on 0773824465, with your child's name and class.",
      "payment_deadline": "",
      "contribution_mode": "either",
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "",
      "bank_account_name": "L C Kumari",
      "bank_name": "BOC",
      "bank_branch": "Rajagiriya",
      "bank_account_number": "5464113",
      "bank_reference": "Child's name and class",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "usa-canada",
      "name": "USA/Canada",
      "sort_order": 3,
      "year_groups": "Year 4",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "Please drop the food on the morning of Friday 16 October 2026, labelled with the stall name and your child's name and class.",
      "packaging_note": "No single-use plastic. Please use cardboard or another recyclable container.",
      "halal_note": "",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "singapore-malaysia-thailand",
      "name": "Singapore/Malaysia/Thailand",
      "sort_order": 4,
      "year_groups": "Year 2",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "sri-lanka",
      "name": "Sri Lanka",
      "sort_order": 5,
      "year_groups": "Nursery and Year 1",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "europe",
      "name": "Europe",
      "sort_order": 6,
      "year_groups": "Playgroup and Reception",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "middle-east",
      "name": "Middle East",
      "sort_order": 7,
      "year_groups": "Year 12",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "china",
      "name": "China",
      "sort_order": 8,
      "year_groups": "Year 6",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "maldives",
      "name": "Maldives",
      "sort_order": 9,
      "year_groups": "Year 11",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "australia-nz-philippines-indonesia",
      "name": "Australia/NZ/Philippines/Indonesia",
      "sort_order": 10,
      "year_groups": "Year 3",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "palestine-un-zone",
      "name": "Palestine and UN Zone",
      "sort_order": 11,
      "year_groups": "Year 9 and Year 13",
      "support_type": "both",
      "amount_per_family": "",
      "how_to_pay": "Last year's details, please confirm.",
      "payment_deadline": "",
      "contribution_mode": "either",
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "Any meat provided should be halal please.",
      "bank_account_name": "Shyam Jobanputra",
      "bank_name": "Commercial Bank",
      "bank_branch": "Narahenpita",
      "bank_account_number": "1220044952",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    },
    {
      "id": "eco-warriors",
      "name": "Eco Warriors",
      "sort_order": 12,
      "year_groups": "Year 8",
      "support_type": "food",
      "amount_per_family": "",
      "how_to_pay": "",
      "payment_deadline": "",
      "contribution_mode": null,
      "food_coordinator_name": "",
      "food_coordinator_phone": "",
      "dropoff_instructions": "",
      "packaging_note": "No single-use plastic.",
      "halal_note": "",
      "bank_account_name": "",
      "bank_name": "",
      "bank_branch": "",
      "bank_account_number": "",
      "bank_reference": "",
      "status": "not_started",
      "locked_at": null,
      "locked_by": null,
      "submitted_at": null,
      "updated_at": null,
      "updated_by": null,
      "updated_by_email": null
    }
  ],
  "dishes": [
    {
      "id": "japan-1",
      "stall_id": "japan",
      "name": "Sushi Roll Veg",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "japan-2",
      "stall_id": "japan",
      "name": "Yakisoba Noodles",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "japan-3",
      "stall_id": "japan",
      "name": "Chicken Teriyaki/Karage",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "japan-4",
      "stall_id": "japan",
      "name": "Matcha Sweets/Cake",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "japan-5",
      "stall_id": "japan",
      "name": "Mochi Sweets",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "japan-6",
      "stall_id": "japan",
      "name": "Senbei Rice Crackers",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "india-1",
      "stall_id": "india",
      "name": "Biriyani (veg)",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "india-2",
      "stall_id": "india",
      "name": "Biriyani (chicken)",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "india-3",
      "stall_id": "india",
      "name": "Chicken gravy and raita",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "india-4",
      "stall_id": "india",
      "name": "Meduvadas",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "india-5",
      "stall_id": "india",
      "name": "Soft paratha",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "india-6",
      "stall_id": "india",
      "name": "Samosa",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "india-7",
      "stall_id": "india",
      "name": "Momos (veg, Nepali)",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "india-8",
      "stall_id": "india",
      "name": "Laddoos",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "india-9",
      "stall_id": "india",
      "name": "Gulab Jamun",
      "diet": "veg",
      "allergens": [
        "dairy"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 9
    },
    {
      "id": "india-10",
      "stall_id": "india",
      "name": "Other Indian sweets",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 10
    },
    {
      "id": "india-11",
      "stall_id": "india",
      "name": "Sel roti (Nepali)",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 11
    },
    {
      "id": "india-12",
      "stall_id": "india",
      "name": "Bundi",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 12
    },
    {
      "id": "usa-canada-1",
      "stall_id": "usa-canada",
      "name": "Waffles with maple syrup",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "usa-canada-2",
      "stall_id": "usa-canada",
      "name": "Mini sausage pastries",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "usa-canada-3",
      "stall_id": "usa-canada",
      "name": "Loaded fries (poutine)",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Please send these in frozen packs so they can be fried on the morning.",
      "sort_order": 3
    },
    {
      "id": "usa-canada-4",
      "stall_id": "usa-canada",
      "name": "Strawberries and mini marshmallows",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "usa-canada-5",
      "stall_id": "usa-canada",
      "name": "Hotdogs",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "usa-canada-6",
      "stall_id": "usa-canada",
      "name": "Donuts",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "usa-canada-7",
      "stall_id": "usa-canada",
      "name": "Cookies",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "usa-canada-8",
      "stall_id": "usa-canada",
      "name": "Pizza",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "singapore-malaysia-thailand-1",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mee Goreng",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "singapore-malaysia-thailand-2",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mini Chicken Satay",
      "diet": "non_veg",
      "allergens": [
        "nuts"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Peanut sauce is common. Note here if you leave it off.",
      "sort_order": 2
    },
    {
      "id": "singapore-malaysia-thailand-3",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Chicken Spring Rolls",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "singapore-malaysia-thailand-4",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mini Wonton Cups",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "singapore-malaysia-thailand-5",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mini Bao Buns",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "singapore-malaysia-thailand-6",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mini Pandan Cupcakes / Mini Milo Cupcakes",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "singapore-malaysia-thailand-7",
      "stall_id": "singapore-malaysia-thailand",
      "name": "Mango Sticky Cups",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "sri-lanka-1",
      "stall_id": "sri-lanka",
      "name": "Milk Rice",
      "diet": "veg",
      "allergens": [
        "dairy"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "sri-lanka-2",
      "stall_id": "sri-lanka",
      "name": "Lunu Miris",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "sri-lanka-3",
      "stall_id": "sri-lanka",
      "name": "Konda Kavum",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "sri-lanka-4",
      "stall_id": "sri-lanka",
      "name": "Kokis",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "sri-lanka-5",
      "stall_id": "sri-lanka",
      "name": "Asmi",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "sri-lanka-6",
      "stall_id": "sri-lanka",
      "name": "Mung Kavum",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "sri-lanka-7",
      "stall_id": "sri-lanka",
      "name": "Hadi Kavum",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "sri-lanka-8",
      "stall_id": "sri-lanka",
      "name": "Naran Kavum",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "sri-lanka-9",
      "stall_id": "sri-lanka",
      "name": "Aluwa",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 9
    },
    {
      "id": "sri-lanka-10",
      "stall_id": "sri-lanka",
      "name": "Wali Thalapa",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 10
    },
    {
      "id": "sri-lanka-11",
      "stall_id": "sri-lanka",
      "name": "Halapa",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 11
    },
    {
      "id": "sri-lanka-12",
      "stall_id": "sri-lanka",
      "name": "Dodol",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 12
    },
    {
      "id": "sri-lanka-13",
      "stall_id": "sri-lanka",
      "name": "Milk Toffee",
      "diet": "veg",
      "allergens": [
        "dairy"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 13
    },
    {
      "id": "sri-lanka-14",
      "stall_id": "sri-lanka",
      "name": "Ala Toffee",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 14
    },
    {
      "id": "sri-lanka-15",
      "stall_id": "sri-lanka",
      "name": "Coconut Toffee",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 15
    },
    {
      "id": "sri-lanka-16",
      "stall_id": "sri-lanka",
      "name": "Pani Walalu",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 16
    },
    {
      "id": "sri-lanka-17",
      "stall_id": "sri-lanka",
      "name": "Undu Wel",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 17
    },
    {
      "id": "sri-lanka-18",
      "stall_id": "sri-lanka",
      "name": "Cup Cakes with SL Flag",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 18
    },
    {
      "id": "sri-lanka-19",
      "stall_id": "sri-lanka",
      "name": "Thala Karali",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 19
    },
    {
      "id": "sri-lanka-20",
      "stall_id": "sri-lanka",
      "name": "Bibikkan",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 20
    },
    {
      "id": "sri-lanka-21",
      "stall_id": "sri-lanka",
      "name": "Tea Buns",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 21
    },
    {
      "id": "sri-lanka-22",
      "stall_id": "sri-lanka",
      "name": "Viana Roll",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 22
    },
    {
      "id": "sri-lanka-23",
      "stall_id": "sri-lanka",
      "name": "Fish Bun",
      "diet": "non_veg",
      "allergens": [
        "seafood"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 23
    },
    {
      "id": "sri-lanka-24",
      "stall_id": "sri-lanka",
      "name": "Mini Pol roti",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 24
    },
    {
      "id": "sri-lanka-25",
      "stall_id": "sri-lanka",
      "name": "King Coconut Water",
      "diet": "vegan",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": null,
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 25
    },
    {
      "id": "sri-lanka-26",
      "stall_id": "sri-lanka",
      "name": "Aggala",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 26
    },
    {
      "id": "sri-lanka-27",
      "stall_id": "sri-lanka",
      "name": "Banana",
      "diet": "vegan",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": null,
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 27
    },
    {
      "id": "europe-1",
      "stall_id": "europe",
      "name": "Mini Pizza (chicken/veg)",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "europe-2",
      "stall_id": "europe",
      "name": "Macarons",
      "diet": "veg",
      "allergens": [
        "nuts"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Fab, via Dinusha 0776383877.",
      "sort_order": 2
    },
    {
      "id": "europe-3",
      "stall_id": "europe",
      "name": "Fruits (grapes or strawberry)",
      "diet": "vegan",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": null,
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Fresh fruit.",
      "sort_order": 3
    },
    {
      "id": "europe-4",
      "stall_id": "europe",
      "name": "Mini Quiche/Pie (chicken/veg)",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "europe-5",
      "stall_id": "europe",
      "name": "Chicken Sausages (cut in small pieces)",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "europe-6",
      "stall_id": "europe",
      "name": "Chicken meat balls",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "europe-7",
      "stall_id": "europe",
      "name": "Mini Donuts",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "europe-8",
      "stall_id": "europe",
      "name": "Mini Cupcakes",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "europe-9",
      "stall_id": "europe",
      "name": "Chocolate Fudge/Cake",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Fab, via Dinusha 0776383877.",
      "sort_order": 9
    },
    {
      "id": "europe-10",
      "stall_id": "europe",
      "name": "Pastries or other savoury items",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Fab, via Dinusha 0776383877.",
      "sort_order": 10
    },
    {
      "id": "middle-east-1",
      "stall_id": "middle-east",
      "name": "Boondi",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "middle-east-2",
      "stall_id": "middle-east",
      "name": "Dates/date cake",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "middle-east-3",
      "stall_id": "middle-east",
      "name": "Barfi",
      "diet": "veg",
      "allergens": [
        "dairy"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "middle-east-4",
      "stall_id": "middle-east",
      "name": "Basbousa",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "middle-east-5",
      "stall_id": "middle-east",
      "name": "Gulab jamun",
      "diet": "veg",
      "allergens": [
        "dairy"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "middle-east-6",
      "stall_id": "middle-east",
      "name": "Chicken Shawarma",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "middle-east-7",
      "stall_id": "middle-east",
      "name": "Chicken kebabs",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "middle-east-8",
      "stall_id": "middle-east",
      "name": "Chickpea salad",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "middle-east-9",
      "stall_id": "middle-east",
      "name": "Punjabi vegetable samosas",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 9
    },
    {
      "id": "middle-east-10",
      "stall_id": "middle-east",
      "name": "Boneless Chicken Biryani",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 10
    },
    {
      "id": "middle-east-11",
      "stall_id": "middle-east",
      "name": "Arabic coffee",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": null,
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 11
    },
    {
      "id": "middle-east-12",
      "stall_id": "middle-east",
      "name": "Rooh Afza",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 12
    },
    {
      "id": "china-1",
      "stall_id": "china",
      "name": "Red bean pumpkin cake",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "china-2",
      "stall_id": "china",
      "name": "Fried Chicken Wings",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "china-3",
      "stall_id": "china",
      "name": "Fried Prawns",
      "diet": "non_veg",
      "allergens": [
        "seafood"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "china-4",
      "stall_id": "china",
      "name": "Chicken and corn dumplings",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "china-5",
      "stall_id": "china",
      "name": "Coconut mango rolls",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "china-6",
      "stall_id": "china",
      "name": "Chinese chicken burger",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "maldives-1",
      "stall_id": "maldives",
      "name": "Handulu Gulha",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "maldives-2",
      "stall_id": "maldives",
      "name": "Fu Gulha",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "maldives-3",
      "stall_id": "maldives",
      "name": "Masroshi",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 3
    },
    {
      "id": "maldives-4",
      "stall_id": "maldives",
      "name": "Bajiya",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 4
    },
    {
      "id": "maldives-5",
      "stall_id": "maldives",
      "name": "Kulhi Boakibaa",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "maldives-6",
      "stall_id": "maldives",
      "name": "Riha Folhi",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "maldives-7",
      "stall_id": "maldives",
      "name": "Kavaabu",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "maldives-8",
      "stall_id": "maldives",
      "name": "Havaadhulee Bis",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 8
    },
    {
      "id": "maldives-9",
      "stall_id": "maldives",
      "name": "Kudhi Gulha",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Last year this was a pack of 5.",
      "sort_order": 9
    },
    {
      "id": "maldives-10",
      "stall_id": "maldives",
      "name": "Dhandi Aluvi Boakibaa",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 10
    },
    {
      "id": "maldives-11",
      "stall_id": "maldives",
      "name": "Huni Gulha",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 11
    },
    {
      "id": "maldives-12",
      "stall_id": "maldives",
      "name": "Githeyo Boakibaa",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 12
    },
    {
      "id": "maldives-13",
      "stall_id": "maldives",
      "name": "Saagu Bondibaiy",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 13
    },
    {
      "id": "maldives-14",
      "stall_id": "maldives",
      "name": "Ulhaali",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 14
    },
    {
      "id": "maldives-15",
      "stall_id": "maldives",
      "name": "Fehi Boakibaa",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 15
    },
    {
      "id": "australia-nz-philippines-indonesia-1",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Sausage Pastry",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 1
    },
    {
      "id": "australia-nz-philippines-indonesia-2",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Chicken Sausages (halal)",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 2
    },
    {
      "id": "australia-nz-philippines-indonesia-3",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Mini Pavlova",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Silver Aisle bakery, 077 510 2583.",
      "sort_order": 3
    },
    {
      "id": "australia-nz-philippines-indonesia-4",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Lamingtons",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Hasna 0772001200. Another number listed last year: 0722435335.",
      "sort_order": 4
    },
    {
      "id": "australia-nz-philippines-indonesia-5",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Tim Tams",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 5
    },
    {
      "id": "australia-nz-philippines-indonesia-6",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Rocky Road",
      "diet": "veg",
      "allergens": [
        "nuts"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 6
    },
    {
      "id": "australia-nz-philippines-indonesia-7",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Fried/Baked chicken wings",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 7
    },
    {
      "id": "australia-nz-philippines-indonesia-8",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Chicken Satay",
      "diet": "non_veg",
      "allergens": [
        "nuts"
      ],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Keep any sauce separate from the chicken. Suggested vendor from last year: Pepper Valley or Crescent.",
      "sort_order": 8
    },
    {
      "id": "australia-nz-philippines-indonesia-9",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Spring Roll",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 9
    },
    {
      "id": "australia-nz-philippines-indonesia-10",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Vege Rice Noodles",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Annalyn, 0769776009.",
      "sort_order": 10
    },
    {
      "id": "australia-nz-philippines-indonesia-11",
      "stall_id": "australia-nz-philippines-indonesia",
      "name": "Chicken pie",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "",
      "sort_order": 11
    },
    {
      "id": "palestine-un-zone-1",
      "stall_id": "palestine-un-zone",
      "name": "Customised Flag Cookies",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Heavenly Bakes, Zeenath 777259249.",
      "sort_order": 1
    },
    {
      "id": "palestine-un-zone-2",
      "stall_id": "palestine-un-zone",
      "name": "Cassava Chips",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Hasana 770285285.",
      "sort_order": 2
    },
    {
      "id": "palestine-un-zone-3",
      "stall_id": "palestine-un-zone",
      "name": "Date Cake",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "sweet",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Paan Paan, Avani 0774103799.",
      "sort_order": 3
    },
    {
      "id": "palestine-un-zone-4",
      "stall_id": "palestine-un-zone",
      "name": "Garlic Bread Rolls",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Paan Paan, Avani 0774103799.",
      "sort_order": 4
    },
    {
      "id": "palestine-un-zone-5",
      "stall_id": "palestine-un-zone",
      "name": "Samosas",
      "diet": null,
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Paan Paan, Avani 0774103799.",
      "sort_order": 5
    },
    {
      "id": "palestine-un-zone-6",
      "stall_id": "palestine-un-zone",
      "name": "Grilled Chicken Skewers",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Dolce Falasteen, Azra 774612999.",
      "sort_order": 6
    },
    {
      "id": "palestine-un-zone-7",
      "stall_id": "palestine-un-zone",
      "name": "Falafel & Hummus",
      "diet": "veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Dolce Falasteen, Azra 774612999.",
      "sort_order": 7
    },
    {
      "id": "palestine-un-zone-8",
      "stall_id": "palestine-un-zone",
      "name": "Mini Shawarma",
      "diet": "non_veg",
      "allergens": [],
      "allergen_other": "",
      "spice": null,
      "taste": "savoury",
      "made_by": "home",
      "caterer_name": "",
      "caterer_contact": "",
      "target_pieces": null,
      "notes": "Suggested vendor from last year: Dolce Falasteen, Azra 774612999.",
      "sort_order": 8
    }
  ]
}
